# Generated by Django 2.0.1 on 2020-04-11 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='назва групи')),
                ('age_group', models.CharField(choices=[('Старша', 'L'), ('Середня', 'M'), ('Молодша', 'S')], max_length=1, verbose_name='вікова група')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='опис групи')),
                ('about_us', models.TextField(blank=True, null=True, verbose_name='про нас')),
            ],
            options={
                'verbose_name': 'Група',
                'verbose_name_plural': 'Групи',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='гурток')),
            ],
            options={
                'verbose_name': 'Гурток',
                'verbose_name_plural': 'Гуртки',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=125, verbose_name="ім'я")),
                ('last_name', models.CharField(max_length=125, verbose_name='прізвище')),
                ('middle_name', models.CharField(blank=True, max_length=125, verbose_name='по-батькові')),
                ('birthday', models.DateField(verbose_name='день народження')),
                ('image', models.ImageField(upload_to='staff/', verbose_name='фото')),
                ('description', models.TextField(blank=True)),
                ('tutor_position', models.CharField(choices=[('Вихователь', 'tutor'), ('Помічник', 'assistant'), ('Психолог', 'psychologist'), ('Муз керівник', 'music'), ('Фіз рук', 'sport')], max_length=15)),
                ('education', models.CharField(blank=True, max_length=250, verbose_name='освіта')),
                ('experience', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='стаж роботи')),
                ('qualification', models.CharField(blank=True, max_length=250, verbose_name='кваліфікація')),
            ],
            options={
                'verbose_name': 'Вихователь',
                'verbose_name_plural': 'Вихователі',
            },
        ),
        migrations.AddField(
            model_name='section',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_tutor', to='staff.Tutor', verbose_name='керівник'),
        ),
        migrations.AddField(
            model_name='group',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_section', to='staff.Section', verbose_name='гурток'),
        ),
        migrations.AddField(
            model_name='group',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_tutor', to='staff.Tutor', verbose_name='вихователь'),
        ),
    ]
