# Generated by Django 2.0.1 on 2020-04-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='age_group',
            field=models.CharField(choices=[('L', 'Старша'), ('M', 'Середня'), ('S', 'Молодша')], max_length=1, verbose_name='вікова група'),
        ),
        migrations.RemoveField(
            model_name='group',
            name='section',
        ),
        migrations.AddField(
            model_name='group',
            name='section',
            field=models.ManyToManyField(related_name='group_section', to='staff.Section', verbose_name='гурток'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='tutor_position',
            field=models.CharField(choices=[('Вихователь', 'tutor'), ('Помічник', 'assistant'), ('Психолог', 'psychologist'), ('Муз керівник', 'music'), ('Фіз рук', 'sport')], max_length=15, verbose_name='посада'),
        ),
    ]
