# Generated by Django 2.0.1 on 2020-04-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200411_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='tutor',
        ),
        migrations.AddField(
            model_name='group',
            name='tutor',
            field=models.ManyToManyField(related_name='group_tutor', to='staff.Tutor', verbose_name='вихователь'),
        ),
    ]
