# Generated by Django 2.0.1 on 2020-04-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20200412_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='опис'),
        ),
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='section/', verbose_name='фото'),
        ),
    ]
