# Generated by Django 2.0.1 on 2020-04-15 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0002_auto_20200414_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='контент')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='створено')),
                ('title', models.CharField(max_length=125)),
                ('is_flash', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name': 'Цитата', 'verbose_name_plural': 'Цитати'},
        ),
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.CharField(max_length=125, verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='content',
            field=models.CharField(max_length=250, verbose_name='цитата'),
        ),
    ]
