# Generated by Django 2.0.1 on 2020-04-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200415_0625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': 'Оголошення', 'verbose_name_plural': 'Оголошення'},
        ),
        migrations.AlterField(
            model_name='notice',
            name='is_flash',
            field=models.BooleanField(default=False, verbose_name='блискавка'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=125, verbose_name='заголовок'),
        ),
    ]
