# Generated by Django 2.0.1 on 2020-04-07 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='назва події')),
                ('created', models.DateField(auto_now_add=True, verbose_name='створено')),
                ('scheduled', models.DateTimeField(blank=True, null=True, verbose_name='дата проведення')),
                ('description', models.CharField(max_length=250, verbose_name='опис')),
                ('content', models.TextField(blank=True, verbose_name='контент')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='назва альбому')),
                ('title_image', models.ImageField(upload_to='title/', verbose_name='титульне фото')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='опис альбому')),
                ('created', models.DateField(auto_now_add=True, verbose_name='створено')),
            ],
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/%d', verbose_name='фото')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_image', to='event.Gallery', verbose_name='галерея')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_event', to='event.Gallery', verbose_name='галерея'),
        ),
    ]
