# Generated by Django 2.0.1 on 2020-04-09 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20200409_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='event.Gallery', verbose_name='галерея'),
        ),
    ]
