# Generated by Django 2.0.1 on 2020-04-10 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20200410_0653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorygallery',
            options={'verbose_name': 'Категорія галереї', 'verbose_name_plural': 'Категорії галерей'},
        ),
    ]
