# Generated by Django 2.0.1 on 2020-04-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_last_name', models.CharField(max_length=50, verbose_name="Ім'я дитини")),
                ('child_first_name', models.CharField(max_length=30, verbose_name='Прізвище дитини')),
                ('child_middle_name', models.CharField(blank=True, max_length=30, verbose_name='По-батькові')),
                ('child_birthday', models.DateField(blank=True, verbose_name='день народження')),
                ('birth_certificate', models.CharField(blank=True, max_length=15, verbose_name='Свідоцтво про народження')),
                ('certificate_issued', models.CharField(blank=True, max_length=125, verbose_name='Ким видане')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='адреса')),
                ('wish_year', models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)], default=0, verbose_name='Рік зарахування')),
                ('parent_last_name', models.CharField(blank=True, max_length=50, verbose_name="Ім'я батька")),
                ('parent_first_name', models.CharField(blank=True, max_length=30, verbose_name='Прізвище батька')),
                ('parent_middle_name', models.CharField(blank=True, max_length=30, verbose_name='По-батькові')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=14)),
                ('privilege', models.PositiveSmallIntegerField(choices=[(3, 'діти воїнів АТО'), (2, 'діти інваліди'), (1, 'діти з багатодітних сімей'), (0, 'на загальних засадах')], verbose_name='пільга')),
                ('created', models.DateField(auto_now_add=True, verbose_name='створено')),
                ('group_age', models.PositiveSmallIntegerField(choices=[(1, 'молодша'), (2, 'середня'), (3, 'старша')], verbose_name='вікова група')),
                ('is_approve', models.BooleanField(default=False)),
            ],
        ),
    ]
